### ISSUE TITLE
TypeError: can't compare offset-naive and offset-aware datetimes

### ISSUE THREAD

**Issue by frekel** [vmtyler/ical-sensor-homeassistant#1]
Any idea how to solve this error:

`````17-01-24 11:04:16 homeassistant.components.sensor: Error while setting up platform ical
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/homeassistant/helpers/entity_component.py", line 151, in _async_setup_platform
    entity_platform.add_entities, discovery_info
  File "/usr/lib/python3.4/asyncio/futures.py", line 388, in __iter__
    yield self  # This tells Task to wait for completion.
  File "/usr/lib/python3.4/asyncio/tasks.py", line 286, in _wakeup
    value = future.result()
  File "/usr/lib/python3.4/asyncio/futures.py", line 277, in result
    raise self._exception
  File "/usr/lib/python3.4/concurrent/futures/thread.py", line 54, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/etc/homeassistant/custom_components/sensor/ical.py", line 36, in setup_platform
    data_object.update()
  File "/usr/local/lib/python3.4/dist-packages/homeassistant/util/__init__.py", line 296, in wrapper
    result = method(*args, **kwargs)
  File "/etc/homeassistant/custom_components/sensor/ical.py", line 114, in update
    events = dateparser(cal,today)
  File "/etc/homeassistant/custom_components/sensor/ical.py", line 57, in dateparser
    if start <= date <= end:
  File "/etc/homeassistant/deps/arrow/arrow.py", line 774, in __ge__
    return self._datetime >= self._get_datetime(other)
TypeError: can't compare offset-naive and offset-aware datetimes
````

Thanks,
Frank

**Comment by vmtyler** [comment]
yes- the issue is your date source- can you give me a sample ics? i need to have it check if it should be TZ aware or not for each feed.

**Comment by frekel** [comment]
````
'BEGIN:VCALENDAR
VERSION:2.0
X-WR-CALNAME:Frank
X-APPLE-CALENDAR-COLOR:#B90E28
BEGIN:VTIMEZONE
TZID:Europe/Amsterdam
X-LIC-LOCATION:Europe/Amsterdam
BEGIN:STANDARD
DTSTART:18350101T000000
RDATE;VALUE=DATE-TIME:18350101T000000
TZNAME:S
TZOFFSETFROM:+1932
TZOFFSETTO:+1932
END:STANDARD
BEGIN:DAYLIGHT
DTSTART:19160501T000000
RDATE;VALUE=DATE-TIME:19160501T000000
RDATE;VALUE=DATE-TIME:19170416T020000
RDATE;VALUE=DATE-TIME:19220326T020000
RDATE;VALUE=DATE-TIME:19230601T020000
RDATE;VALUE=DATE-TIME:19240330T020000
RDATE;VALUE=DATE-TIME:19250605T020000
RDATE;VALUE=DATE-TIME:19320522T020000
RDATE;VALUE=DATE-TIME:19370522T020000
TZNAME:NST
TZOFFSETFROM:+1932
TZOFFSETTO:+011932
END:DAYLIGHT
BEGIN:STANDARD
DTSTART:19161001T000000
RDATE;VALUE=DATE-TIME:19161001T000000
RDATE;VALUE=DATE-TIME:19170917T030000
TZNAME:AMT
TZOFFSETFROM:+011932
TZOFFSETTO:+1932
END:STANDARD
BEGIN:DAYLIGHT
DTSTART:19180401T020000
RRULE:FREQ=YEARLY;UNTIL=19210404T014028Z;BYDAY=1MO;BYMONTH=4
TZNAME:NST
TZOFFSETFROM:+1932
TZOFFSETTO:+011932
END:DAYLIGHT
BEGIN:STANDARD
DTSTART:19180930T030000
RRULE:FREQ=YEARLY;UNTIL=19210926T014028Z;BYDAY=-1MO;BYMONTH=9
TZNAME:AMT
TZOFFSETFROM:+011932
TZOFFSETTO:+1932
END:STANDARD
BEGIN:STANDARD
DTSTART:19221008T030000
RRULE:FREQ=YEARLY;UNTIL=19361004T014028Z;BYDAY=SU;
 BYMONTHDAY=2,3,4,5,6,7,8;BYMONTH=10
TZNAME:AMT
TZOFFSETFROM:+011932
TZOFFSETTO:+1932
END:STANDARD
BEGIN:DAYLIGHT
DTSTART:19260515T020000
RRULE:FREQ=YEARLY;UNTIL=19310515T014028Z;BYMONTH=5
TZNAME:NST
TZOFFSETFROM:+1932
TZOFFSETTO:+011932
END:DAYLIGHT
BEGIN:DAYLIGHT
DTSTART:19330515T020000
RRULE:FREQ=YEARLY;UNTIL=19360515T014028Z;BYMONTH=5
TZNAME:NST
TZOFFSETFROM:+1932
TZOFFSETTO:+011932
END:DAYLIGHT
BEGIN:STANDARD
DTSTART:19370701T000000
RDATE;VALUE=DATE-TIME:19370701T000000
TZNAME:NEST
TZOFFSETFROM:+011932
TZOFFSETTO:+0120
END:STANDARD
BEGIN:STANDARD
DTSTART:19371003T030000
RRULE:FREQ=YEARLY;UNTIL=19391008T014000Z;BYDAY=SU;
 BYMONTHDAY=2,3,4,5,6,7,8;BYMONTH=10
TZNAME:NET
TZOFFSETFROM:+0120
TZOFFSETTO:+0020
END:STANDARD
BEGIN:DAYLIGHT
DTSTART:19380515T020000
RRULE:FREQ=YEARLY;UNTIL=19390515T014000Z;BYMONTH=5
TZNAME:NEST
TZOFFSETFROM:+0020
TZOFFSETTO:+0120
END:DAYLIGHT
BEGIN:STANDARD
DTSTART:19400516T000000
RDATE;VALUE=DATE-TIME:19400516T000000
TZNAME:CEST
TZOFFSETFROM:+0020
TZOFFSETTO:+0200
END:STANDARD
BEGIN:STANDARD
DTSTART:19421102T030000
RDATE;VALUE=DATE-TIME:19421102T030000
RDATE;VALUE=DATE-TIME:19431004T030000
RDATE;VALUE=DATE-TIME:19441002T030000
RDATE;VALUE=DATE-TIME:19450916T030000
RDATE;VALUE=DATE-TIME:19770925T030000
RDATE;VALUE=DATE-TIME:19781001T030000
TZNAME:CET
TZOFFSETFROM:+0200
TZOFFSETTO:+0100
END:STANDARD
BEGIN:DAYLIGHT
DTSTART:19430329T020000
RDATE;VALUE=DATE-TIME:19430329T020000
RDATE;VALUE=DATE-TIME:19440403T020000
RDATE;VALUE=DATE-TIME:19450402T020000
TZNAME:CEST
TZOFFSETFROM:+0100
TZOFFSETTO:+0200
END:DAYLIGHT
BEGIN:STANDARD
DTSTART:19770101T000000
RDATE;VALUE=DATE-TIME:19770101T000000
TZNAME:CEST
TZOFFSETFROM:+0100
TZOFFSETTO:+0100
END:STANDARD
BEGIN:DAYLIGHT
DTSTART:19770403T020000
RRULE:FREQ=YEARLY;UNTIL=19800406T010000Z;BYDAY=1SU;BYMONTH=4
TZNAME:CEST
TZOFFSETFROM:+0100
TZOFFSETTO:+0200
END:DAYLIGHT
BEGIN:STANDARD
DTSTART:19790930T030000
RRULE:FREQ=YEARLY;UNTIL=19950924T010000Z;BYDAY=-1SU;BYMONTH=9
TZNAME:CET
TZOFFSETFROM:+0200
TZOFFSETTO:+0100
END:STANDARD
BEGIN:DAYLIGHT
DTSTART:19810329T020000
RRULE:FREQ=YEARLY;BYDAY=-1SU;BYMONTH=3
TZNAME:CEST
TZOFFSETFROM:+0100
TZOFFSETTO:+0200
END:DAYLIGHT
BEGIN:STANDARD
DTSTART:19961027T030000
RRULE:FREQ=YEARLY;BYDAY=-1SU;BYMONTH=10
TZNAME:CET
TZOFFSETFROM:+0200
TZOFFSETTO:+0100
END:STANDARD
END:VTIMEZONE
BEGIN:VEVENT
ATTENDEE;CN=Hotmail;CUTYPE=INDIVIDUAL:mailto:joffreyhoijer@email.org
ATTENDEE;CN=frank@email.nl;CUTYPE=INDIVIDUAL:mailto:
 frank@email.nl
DESCRIPTION:Tijd: woensdag 13 juli 2011 16:00-17:00 (UTC+01:00) 
 Amsterdam\, Berlijn\, Bern\, Rome\, Stockholm\, Wenen.\n\nOpmerking: in 
 de GMT-offset hierboven is geen rekening gehouden met correcties voor de 
 zomertijd.\n\n*~*~*~*~*~*~*~*~*~*\n\n\n
DTEND:20110713T150000Z
DTSTAMP:20111228T180820Z
DTSTART:20110713T140000Z
LAST-MODIFIED:20110707T125525Z
ORGANIZER;CN=M.Elsenga - email.com -;SCHEDULE-STATUS=1.1:mailto:
 melsenga@email.com
SEQUENCE:0
SUMMARY:Gesprek stagaire multimedia design
TRANSP:OPAQUE
UID:011BF3C0-BA88-4C0A-A7EA-4B3D3DE2A082
BEGIN:VALARM
ACTION:DISPLAY
DESCRIPTION:Event reminder
TRIGGER;VALUE=DURATION:-PT15M
X-WR-ALARMUID:F6A352F4-3ECD-486D-B6E8-1D1B489A0AAD
END:VALARM
END:VEVENT
BEGIN:VEVENT
CREATED:20161128T062429Z
DTEND;VALUE=DATE:20161202
DTSTAMP:20161128T062430Z
DTSTART;VALUE=DATE:20161201
LAST-MODIFIED:20161128T062429Z
SEQUENCE:0
SUMMARY:Lily neusamandelen
UID:01B02848-484F-4AEB-BC3D-DED6ABC7D73C
END:VEVENT
BEGIN:VEVENT
CREATED:20160702T100055Z
DTEND;TZID=Europe/Amsterdam:20160829T090000
DTSTAMP:20160702T100056Z
DTSTART;TZID=Europe/Amsterdam:20160829T080000
LAST-MODIFIED:20160702T100055Z
LOCATION:De Optimist Thuis
SEQUENCE:0
SUMMARY:Weer naar school
UID:033BD625-2F5A-4423-AE08-1F9FF1087AE0
X-APPLE-STRUCTURED-LOCATION;VALUE=URI;X-ADDRESS=Addres;X-APPLE-ABUID="ab://De%20Optimist%20Thuis";
 X-APPLE-RADIUS=0;X-APPLE-REFERENCEFRAME=1;X-TITLE=De Optimist Thuis:geo:
 52.310342,4.639177
END:VEVENT````

**Comment by frekel** [comment]
@vmtyler: Any luck with fixing? ;)

**Comment by vmtyler** [comment]
I’m having trouble reproducing. What OS are you running HASS on?


On January 27, 2017 at 3:41:44 PM, Frank (notifications@github.com) wrote:

@vmtyler: Any luck with fixing? ;)

**Comment by frekel** [comment]
I am on Rasbian (Jessie)

**Comment by frekel** [comment]
Sorry to bump this again, but I really would like to use your hard work! 
Can I help in any way?

**Comment by vmtyler** [comment]
Can you turn on debug logging and try it again? i need a bit more info.


On January 30, 2017 at 1:20:40 PM, Frank (notifications@github.com) wrote:

Sorry to bump this again, but I really would like to use your hard work!
Can I help in any way?

**Comment by frekel** [comment]
Strange!  With the debug on I get the same details...
Can tell me what you think it is? Then I can do some trail/error things!

Again: Thanks for the help!

````
17-01-30 22:47:49 homeassistant.components.sensor: Error while setting up platform ical
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/homeassistant/helpers/entity_component.py", line 151, in _async_setup_platform
    entity_platform.add_entities, discovery_info
  File "/usr/lib/python3.4/asyncio/futures.py", line 388, in __iter__
    yield self  # This tells Task to wait for completion.
  File "/usr/lib/python3.4/asyncio/tasks.py", line 286, in _wakeup
    value = future.result()
  File "/usr/lib/python3.4/asyncio/futures.py", line 277, in result
    raise self._exception
  File "/usr/lib/python3.4/concurrent/futures/thread.py", line 54, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/etc/homeassistant/custom_components/sensor/ical.py", line 36, in setup_platform
    data_object.update()
  File "/usr/local/lib/python3.4/dist-packages/homeassistant/util/__init__.py", line 296, in wrapper
    result = method(*args, **kwargs)
  File "/etc/homeassistant/custom_components/sensor/ical.py", line 114, in update
    events = dateparser(cal,today)
  File "/etc/homeassistant/custom_components/sensor/ical.py", line 57, in dateparser
    if start <= date <= end:
  File "/etc/homeassistant/deps/arrow/arrow.py", line 774, in __ge__
    return self._datetime >= self._get_datetime(other)
TypeError: can't compare offset-naive and offset-aware datetimes
````

**Comment by vmtyler** [comment]
This part of the code compares today/tomorrow’s date with each of the events in your feed. The error is saying it’s trying to compare a date/time with timezone info with one without. Try this-
use this url and see what happens: 
https://gist.githubusercontent.com/vmtyler/563b9dd53b530ea1204273ff38e836c3/raw/6a037ae6e7cffac664716fa9262e490a251b47e8/test.ics


On January 30, 2017 at 5:00:59 PM, Frank (notifications@github.com) wrote:

Strange! With the debug on I get the same details...
Can tell me what you think it is? Then I can do some trail/error things!

Again: Thanks for the help!

17-01-30 22:47:49 homeassistant.components.sensor: Error while setting up platform ical
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/homeassistant/helpers/entity_component.py", line 151, in _async_setup_platform
    entity_platform.add_entities, discovery_info
  File "/usr/lib/python3.4/asyncio/futures.py", line 388, in __iter__
    yield self  # This tells Task to wait for completion.
  File "/usr/lib/python3.4/asyncio/tasks.py", line 286, in _wakeup
    value = future.result()
  File "/usr/lib/python3.4/asyncio/futures.py", line 277, in result
    raise self._exception
  File "/usr/lib/python3.4/concurrent/futures/thread.py", line 54, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/etc/homeassistant/custom_components/sensor/ical.py", line 36, in setup_platform
    data_object.update()
  File "/usr/local/lib/python3.4/dist-packages/homeassistant/util/__init__.py", line 296, in wrapper
    result = method(*args, **kwargs)
  File "/etc/homeassistant/custom_components/sensor/ical.py", line 114, in update
    events = dateparser(cal,today)
  File "/etc/homeassistant/custom_components/sensor/ical.py", line 57, in dateparser
    if start <= date <= end:
  File "/etc/homeassistant/deps/arrow/arrow.py", line 774, in __ge__
    return self._datetime >= self._get_datetime(other)
TypeError: can't compare offset-naive and offset-aware datetimes

**Comment by frekel** [comment]
Yes. This url is working. 
I will look at the differences in the sources.  Keep you posted!

**Comment by frekel** [comment]
I have updated HomeAssistant to 0.37 and now it is working like a charm.....
Very strange......

I can't test anymore so if you want, close this issue for now.
